# Site settings
title: 'Welcome Home' 
tagline: 'The Homestead Story' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: / # the subpath of your site, e.g. /blog/
